### ISSUE TITLE
Strange iTunes behaviour

### ISSUE THREAD

**Issue by Andres-Brito** [cormiertyshawn895/Retroactive#103] opened 2020-06-25 17:53 UTC
This is the weirdest thing I've been witness since I instralled Retroactive: in random ocassions, iTunes adds the last few seconds of the song to the file of the song that is playing. Does anyone lived something like this as well?

**Comment by cormiertyshawn895** [comment] 2020-06-27 06:12
Duplicate of #92

**Closed as completed by cormiertyshawn895** 2020-06-27 06:12 UTC
Labels: itunes compatibility
