### ISSUE TITLE
iTunes quit unexpectedly.

### ISSUE THREAD

**Issue by RR19840** [cormiertyshawn895/Retroactive#177] opened 2020-12-27 14:19 UTC
hey guys,
just got my new macbook pro m1, and iTunes doesn't open.
i tried all versions on retroactive!

any solution? i need my iTunes!

Process:               iTunes [3948]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [3945]
Responsible:           bash [3945]
User ID:               501

Date/Time:             2020-12-27 09:17:54.602 -0500
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        95D0E3D3-C02B-47E2-ABAF-2BCED3F69B0A

Sleep/Wake UUID:       AB25770F-CA84-424A-8BB1-23F73421BB06

Time Awake Since Boot: 7100 seconds
Time Since Wake:       1100 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x0000000307fcfab0   pc: 0x00007ffdffbb446c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5879
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro17,1, BootROM 6723.61.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Oct 20 2020 12:49:54 version 18.20.222.14.7.8.100 FWID 01-ba327c2d
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: easystore 25FC
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0

**Comment by Shadester** [comment] 2020-12-29 02:55
Same for me. Looks lite crashes due to `EXC_CRASH (Code Signature Invalid)`

**Comment by Shadester** [comment] 2020-12-29 03:04
Duplicate of #168

**Comment by MelloMikeUK** [comment] 2021-02-15 12:48
Hi guys? Did you get anywhere with this? I'm having the same issue.

**Comment by cormiertyshawn895** [comment] 2022-09-02 04:27
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

**Closed as completed by cormiertyshawn895** 2022-09-02 04:27 UTC
