### ISSUE TITLE
iTunes 12.4.3 would be amazing

### ISSUE THREAD

**Issue by iamnotscavullo** [cormiertyshawn895/Retroactive#66] opened 2020-04-03 23:45 UTC
Please, consider iTunes 12.4.3. This version is the best looking version and the last with custom color background  for albums and movies.
Best regards friend.

**Comment by ShikiSuen** [comment] 2020-04-04 19:22
I have the same request, too.

**Comment by DimitarNestorov** [comment] 2020-04-05 06:33
Duplicate: #21

**Comment by cormiertyshawn895** [comment] 2020-04-22 04:54
Duplicate of #21

**Closed as completed by cormiertyshawn895** 2020-04-22 04:54 UTC
