### ISSUE TITLE
App crashes on 12.2

### ISSUE THREAD

**Issue by Denisxiang** [cormiertyshawn895/Retroactive#273] opened 2022-02-09 11:31 UTC
the app crashes on macOS Monterey 12.2 whenever I open it, it quits on me on startup on my M1 mac

**Comment by Denisxiang** [comment] 2022-02-09 11:32
it would be helpful if someone who has a developer mind can either contribute to this project or make a fork of this

**Comment by holtkamp** [comment] 2022-03-09 16:16
Seems to be related / duplicate of #268

**Comment by cormiertyshawn895** [comment] 2022-09-02 04:45
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

**Closed as completed by cormiertyshawn895** 2022-09-02 04:45 UTC
