### ISSUE TITLE
iTunes 12.9.5 crashing on Monterey 12.0.1 on MacBook Pro

### ISSUE THREAD

**Issue by inklaar** [cormiertyshawn895/Retroactive#251] opened 2021-11-02 16:44 UTC
On the new MacBook Pro it is possible to install and run iTunes 12.6.5 and 11.4. 

The latest version 12.9.5 however crashes upon opening. I will attach the error report, but could not help spotting this in one of the lines :-/ (yes, including the ASCII art)

Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

[Problem report.txt](https://github.com/cormiertyshawn895/Retroactive/files/7462522/Problem.report.txt)

**Comment by tocotronaut** [comment] 2021-11-03 11:30
This Bug is well Known.
**iTunes 12.9.5 did never run on any Apple Silicon Processor.**

Duplicate of
https://github.com/cormiertyshawn895/Retroactive/issues/234
https://github.com/cormiertyshawn895/Retroactive/issues/233
https://github.com/cormiertyshawn895/Retroactive/issues/212
https://github.com/cormiertyshawn895/Retroactive/issues/200
https://github.com/cormiertyshawn895/Retroactive/issues/189
https://github.com/cormiertyshawn895/Retroactive/issues/187
https://github.com/cormiertyshawn895/Retroactive/issues/177
https://github.com/cormiertyshawn895/Retroactive/issues/168
and probably some more...

You need to use an older iTunes (Which means you'll need to use an older Database as well or reimport all Music.)

**Comment by cormiertyshawn895** [comment] 2022-09-02 04:23
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

**Closed as completed by cormiertyshawn895** 2022-09-02 04:23 UTC
