### ISSUE TITLE
not all picture are shown...(Big Sur 11.0.1)

### ISSUE THREAD

**Issue by Tauchjoschl** [cormiertyshawn895/Retroactive#152] opened 2020-11-15 12:07 UTC
only some pictures  of an album are shown at the same time. if you scroll, next picture are loading very very slow. if you scroll back, the pictures are loading very very slow again and so on... 
System is Big Sur 11.0.1. Aperture new loaded, Retroactive new loaded etc...
sorry for my bad English...

**Comment by ghost** [comment] 2020-11-15 18:39
Same Problem here. Big Sur 11.0.1

**Comment by Tauchjoschl** [comment] 2020-11-16 06:34
System ist MacBook Air (Retina, 13 Zoll, 2020, i5). With Catalina all was fine. Tested old an new Aperture files. all the same with Big Sur. Only the full screen mode (f-key) ist working well. The browser mode will not run properly...

**Comment by ghost** [comment] 2020-11-17 09:49
My system is MacBook Air (2020 i5), Cleanistall Big Sur 11.0.1
AND
iMac 5K (2019 i5) , Update from Catalina

**Comment by jb59** [comment] 2020-11-19 11:19
Same issue here - MBA 2013 and iMac 5k 2015 - both upgrade installs of Big Sur.

Have to add, just so happy it works at all!!!!!!!

**Comment by hubcapboy** [comment] 2020-11-20 16:26
Same issue... Commenting here to follow any fixes or optimizations.  2018 Mac mini i5, 32 GB ram, RX 5700 XT, library is on a TB3 drive that Blackmagic reports as 2500 MB/s read speed, 50% capacity.

It doesn't seem like a load-time issue... scrolling to the end of the available previews gives you grey space, the scroll bar is aware of the total number of images, and you can scroll past the end of what's displayed. Sometimes clicking in this space will immediately display another "block" of previews.

Using the split view instead of the browser has a similar symptom... I can scroll off to to the side of what's displayed and clicking in the space loads the images immediately.

Looking at activity monitor, Aperture only seems to ever use 2 gb of ram (within 5%) during operation.  Relative to what Aperture was expecting from 2006-2012 I have truckloads of ram that it isn't asking for.

**Comment by uncoday** [comment] 2020-11-26 22:32
I am having the same issue. Hope someone finds a fix for this as I really want to continue using Aperture if at all possible.

**Comment by michaelherger** [comment] 2020-11-27 10:41
I'm seeing the same. But sometimes I'm under the impression that mouse movements have an influence. Eg. move you mouse back over an area with images shown, and the empty space would fill up.

https://www.dropbox.com/s/oti1b0dxmhk7u3b/aperture.mov?dl=0

This is on a MB Air 11" Early 2014, running macOS 11.1 Beta

**Comment by hubcapboy** [comment] 2020-12-22 06:11
After more time with this... 

If I scroll through with the keyboard cursor (which is basically as fast for everything as long as I'm not scrolling through *all* photos in my library) the previews load with no issues. There's definitely some force-refresh action that isn't always occurring when using the scroll wheel.

**Comment by jb59** [comment] 2020-12-22 10:50
The above mouse/trackpad Vs cursor also same for me (MacBook Air, 13" Mid 2013.) Also just noticed the loupe - works in the sense that a magnified area of the image appears, but the usual loupe "frame" doesn't appear (or is transparent) Magnification percentage appears, with options available upon click.

**Comment by bpieber** [comment] 2021-04-04 15:20
As a workaround I press Tab twice.

**Comment by hubcapboy** [comment] 2021-05-21 16:59
The tab trick works for me seems to work 100%... refreshes all thumbnails that should be on the screen. Tab doesn't seem to be on any list of Aperture shortcuts that I can find, so I guess it's just using the default browser function of cycling through available windows/fields?  I was previously doing this by clicking in and out of the blank spaces.

Honestly this bug is *mostly* irritating because it's hard to know if I'm done loading my folder or if I'm waiting for another chunk to load.

**Comment by skiss9** [comment] 2021-05-29 01:31
Same issue here. One press on tab does fix it. At least that's a workaround. Would be great if someone found a fix as this is to me the main bug getting in your way. Considering switching to another app just for this one bug lol.

**Comment by hubcapboy** [comment] 2021-06-01 16:16
If nothing else, Retroactive allowed me to run aperture and successfully
migrate while running Big Sur, all on the same machine while I ran this:

https://www.dpreview.com/news/6731077297/avalanche-can-now-convert-aperture-lightroom-catalogs-for-use-with-luminar-ai

...and confirmed that everything came into Capture One.  I can keep
aperture installed and my old library around for panic moments, but this
would have been a LONG process on the 2012 machine that I was keeping alive
just to run Aperture.

**Comment by Melonking906** [comment] 2021-08-07 17:30
Same issue still on 11.5.1 on a 2018 mini. Holding down tab while the programs open is a work around but its a bit annoying. Also resizing the window causes a reload and works around the issue too.

**Comment by cormiertyshawn895** [comment] 2024-08-11 04:01
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Closed as not planned by cormiertyshawn895** 2024-08-11 04:01 UTC
Labels: aperture compatibility
