### ISSUE TITLE
iTunes 12.9.5 quits unexpectedly on macOS Sonoma after installing

### ISSUE THREAD

**Issue by SchneHa** [cormiertyshawn895/Retroactive#419] opened 2024-02-20 17:53 UTC
I'm not able to install iTunes on macOS Sonoma using Retroactive.

**Comment by Woolwit** [comment] 2024-03-01 00:40
Final Update (I promise! This thread at least)
The story so far...
Upgrading from Monterey to Sonoma 14.3.1 broke my ability to load podcasts from iTunes 11.4. into my 4th Gen iPod Shuffles (I have 3). That night I experimented with using Finder to load podcasts/music into my iPods. I found the experience frustrating and so the next day I downloaded Retroactive 2.1. and used it to install iTunes 12.6.5. I thought all was well until I discovered that only 1 of my 3 iPods was loading playlists from iTunes. Today I confirmed my suspicion that it was something to do with Finder and iPod settings that was preventing iTunes from loading new playlists into the affected iPods. When in Finder I chose to add a single podcast episode from a single podcast, which proved successful, AND THEN tried to add a playlist of podcast episodes through iTunes, it worked. I did not get the 'iTunes could not copy "Podcast Episode" to the iPod "John's iPod" because not enough free space was available.' error message.
So at the end of the day, iTunes 12.6.5, installed via Retroactive 2.1 into an M1 Mac Mini running Sonoma 14.3.1 is working, at least from the perspective of downloading podcasts and loading them into my iPod. 
________
Update 3
Well I'm really confused now. I have 3 iPod Shuffles and one of them works fine with iTunes 11.6.5 but the other two I get the 'iTunes could not copy "Podcast Episode" to the iPod "John's iPod" because not enough free space was available'. I'm just guessing now, but the only difference in the Shuffles is that I tried them out loading with Finder? In Finder they show as empty, 2GB available. I even tried cloning (CCC) the one that was working over to one of the other ones. The clone worked, i.e. same ID and content, but got the same error message. I'm baffled, and frustrated with Mac in general - like wtf can't I load my iPod from the Podcasts app? I will probably find another way to do this.
_______
Update2
It's a few days later and things are broken again. I know for a fact I was able to add a new playlist to my Shuffle running iTunes 11.6.5, but now, a few days later I'm getting an error, on an empty, Restored ipod...
iTunes could not copy "Podcast Episode" to the iPod "John's iPod" because not enough free space was available. From the sounds of it, upgrading to 12.9.5 won't help.
FWIW, getting the "unknown error (-42408)" when I launch iTunes.
Very frustrating... managing and downloading Podcasts working fine. 
______
Update!
I installed Retroactive 2.1 and was able to regain access to my iPod Shuffles when I upgraded from iTunes 11.4 to 11.6.5.3 (downloaded through Retroactive). It's a bit sluggish and I'm seeing the beach ball (which had finally gone away with 11.4 on an M1 Mac Mini), but I'm back and very happy about that. 
I had spent a few hours  working through Shawn's supported apps for iTunes list last night. Which was very frustrating. In that my iTunes (11.4) was still able to manage subscriptions and download podcasts, the issue for me was getting them on my Shuffle. I tried WALTR pro, which kind of worked but only let you load 10 items before needing to get paid for, AnyTrans, and iMazing which didn't see my Shuffle.
The most promising bit of kit was a python3 script https://github.com/nims11/IPod-Shuffle-4g. You enable disk use, load your Shuffle with mp3s (in my case) then point the script to your device and it builds the requisite DB for the Shuffle to work. I then built a smart folder that checked my Mac for Music/mp3 + Date added/ within last 3 days. So that recently downloaded podcast episodes would be easy to find. It worked a charm. I would have dug a bit deeper into it to find out if it were possible to also set the 'remember position' flag somehow, and also to put them in a playlist. But in the meantime I discovered that upgrading to iTunes 11.6.5 solved my problem.
Thanks again Shawn for Retroactive!!
______
I just updated my M1 Mac Mini from Monterey to Sonoma 14.3.1. I had been putting off the update for months in fear of losing the use of iTunes, which I use primarily for managing my podcast addiction. 
iTunes 11.4(18) 64-bit will open and download podcasts I've subscribed to. But when I go to load them into my shuffle it always reports that there is not enough room and then quits.

**Comment by ylluminate** [comment] 2024-03-21 00:28
While I can still use it on my MacBookPro18,2 with Sonoma 14.4, I would recommend moving to Swinsian 3.0 Preview 13 (595). This is proving to be far superior to iTunes in essentially every meaningful way for me and I was able to import a large iTunes library into without any problems. Great developer to boot - cares about his app and is responsive.

**Comment by Woolwit** [comment] 2024-03-22 05:00
Trying Swinsian 3.0 now and feels encouraging. Thanks! I initially downloaded the current stable version which wouldn't let me build a playlist for my iPod Shuffle (which was recognized). Then I found this in a Reddit thread...

> Holding the Option key whilst selecting Swinsian | Check For Updates will show Check For Updates (Beta).

3.0 Let's me build a podcast playlist and load it into my iPod.

**Comment by ylluminate** [comment] 2024-03-22 15:02
Yeah, 3.0 preview is the game changer in my opinion.

**Comment by bjoehy** [comment] 2024-04-06 19:39
iTunes 12.9.5 works as a charm on macos 13.6.6 (thanks [cormiertyshawn895] and God, because I've got very extensive 3T+ library of spoken word and music). I've tried to install for a friend of mine on his brand new M2 MBA with macOS 14.3 and after the installation via Retroactive 2.1, the iTunes normally worked.

Then I ran 14.4 update and since then the iTunes just crash immediatelly after launching attempt.
Have somebody met this issue?
<img width="682" alt="itunes crash sonoma 14 4 (1)" src="https://github.com/cormiertyshawn895/Retroactive/assets/166251189/18a2dae4-ee65-41da-86dc-0024ae03cd46">

**Comment by Woolwit** [comment] 2024-04-06 21:03
Trying Swinsian 3.0 now and feels encouraging. Thanks! I initially downloaded the current stable version which wouldn't let me build a playlist for my iPod Shuffle (which was recognized). Then I found this in a Reddit thread...

> Holding the Option key whilst selecting Swinsian | Check For Updates will show Check For Updates (Beta).

3.0 Let's me build a podcast playlist and load it into my iPod.

> Yeah, 3.0 preview is the game changer in my opinion.

Unfortunately, I was wrong about Swinsian and podcast playlists. From James Burton (Swinsian developer)

> It isn't possible to add podcasts to playlists I'm afraid. That wasn't possible in earlier version either.
The podcasts side of the app has been a bit neglected. I'll try and make some improvements to it once version 3 is officially released. 

My current workaround is iTunes(Retroactive) for managing subscriptions to and downloading podcast episodes. A Smart Folder that recognizes recently downloaded mp3s, which makes them easy to find in Apple Music > Add to library (where I let the files live where they are rather than copy them in to the Music library) where I can build a playlist. Then using Finder to sync the playlist to my ipod. It's kind of a nightmare, but it works.

**Comment by cormiertyshawn895** [comment] 2024-08-11 03:40
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Closed as not planned by cormiertyshawn895** 2024-08-11 03:40 UTC
