### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by berrald** [cormiertyshawn895/Retroactive#73] opened 2020-04-22 11:39 UTC
I can use Aperture again!
How can I make a donation to thank you?

**Comment by paul-hand** [comment] 2020-04-22 13:01
+1 for that. Absolutely thrilled and looking to send a donation ...

Cheers

**Comment by cormiertyshawn895** [comment] 2020-04-24 05:42
Duplicate of #20 

Thank you for your generosity! ❤️

I am super happy to hear Retroactive is able to help you with your photography workflows. Currently, this project does not take any donations.

**Closed as completed by cormiertyshawn895** 2020-04-24 05:42 UTC
