### ISSUE TITLE
Aperture not listing photos in Aperture library on external drive?

### ISSUE THREAD

**Issue by jclev747** [cormiertyshawn895/Retroactive#132] opened 2020-09-30 20:34 UTC
Thanks for working on a solution to keeping Aperture going!

I just installed Retroactive 1.9 after discovering it. 

I am on MacOs 10.15.6 on a MacBook Pro, 16-inch, 2019. I have my Aperture library on an external drive connected by USB-C, formatted GUID, MacOs Extended(Journaled) as I copied it from an old Mac Pro with Mojave.

When I try to import it in Aperture, Aperture displays the external drive and the directories on it. However, when I click on the directory with the library, nothing shows on the file section; not the library itself or any content. Aperture displays photos in the MacHD picture directory.

Can you help with this?

**Comment by jclev747** [comment] 2020-09-30 20:36
I should mention that I am using Aperture 3.6

**Comment by jclev747** [comment] 2020-09-30 20:46
I have also realized that it is not recognizing Aperture Libraries on MacHD or the external drive with the extension .aplibrary, but it does find jpgs, tiffs, pdfs, etc.

**Comment by cormiertyshawn895** [comment] 2020-11-22 11:34
Thank you for your feedback.This looks like a duplicate of #145. 

[Retroactive 1.9 (Build 85) and later](https://github.com/cormiertyshawn895/Retroactive/releases/) added an option to optimize Aperture for macOS Catalina, which improves stability and re-enables the ability to import photos from removable volumes such as SD cards.
<img width="1123" alt="optimize-for-catalina" src="https://user-images.githubusercontent.com/57056759/99198587-865b6100-274e-11eb-9a6c-482b421c818a.png">

Please [download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/), unlock Aperture again, and choose "Optimize for macOS Catalina".

**Closed as completed by cormiertyshawn895** 2020-11-22 11:34 UTC
