### ISSUE TITLE
Unlock Xcode 12

### ISSUE THREAD

**Issue by Mac-Man-APH** [cormiertyshawn895/Retroactive#136] opened 2020-10-09 05:45 UTC
Could you please add the ability to unlock the latest version of Xcode as like many others I am stuck on Mojave but cannot use version Xcode  12 and use the new features in iOS14.

Thanks in advance.

**Comment by cormiertyshawn895** [comment] 2020-11-22 11:31
Xcode 12 requires the Combine framework, which isn't available in macOS Mojave. It will be quite challenging to unlock Xcode 12 on macOS Mojave.

**Comment by cormiertyshawn895** [comment] 2020-11-22 11:32
Duplicate of #128.

**Closed as completed by cormiertyshawn895** 2020-11-22 11:32 UTC
